version: "3.0"

services:
  db:
    image: mongo
    container_name: mongocontainer
  api-pda:
    container_name: pdacontainer
    build: .
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://db:27017/ufjf
    ports:
      - "3001:8080"
    depends_on:
      - db
